import google.generativeai as genai
import time
from typing import Dict, Any
from dotenv import load_dotenv
import os
load_dotenv()


GEMINI_API_KEY=os.getenv("GEMINI_API_KEY")

def configure_gemini(api_key: str):
    """Configure Gemini API with the provided key."""
    genai.configure(api_key=api_key)
    return genai.GenerativeModel('gemini-2.0-flash')

def generate_blog_with_gemini(selected_result: Dict[Any, Any]) -> str:
    """Generate a comprehensive blog post using Gemini API based on selected research result."""

    try:
        # Configure Gemini
        model = configure_gemini(GEMINI_API_KEY)
        
        # Extract information from selected result
        url = selected_result.get('url', '')
        title = selected_result.get('title', '')
        description = selected_result.get('description', '')
        keyword = selected_result.get('keyword', '')
        
        # Create comprehensive prompt for blog generation
        prompt = f"""
        You are an expert content writer and SEO specialist. Based on the following research data, create a comprehensive, engaging, and SEO-optimized blog post.

        RESEARCH DATA:
        - Target Keyword: {keyword}
        - Source URL: {url}
        - Page Title: {title}
        - Page Description: {description}

        BLOG POST REQUIREMENTS (Aligned with Google Search Quality Rater Guidelines):
        1. Purpose & User Intent**: Make sure the blog fully satisfies the informational intent behind "{keyword}" and genuinely helps readers.
        2. EEAT Principles:
        - Show experience with practical examples, case studies, or step-by-step guidance.
        - Demonstrate expertise with accurate, detailed explanations.
        - Build authoritativeness by referencing credible sources ([Link: topic]) where needed.
        - Establish trust by keeping information clear, honest, and reliable.
        3. Page Quality:
        - Ensure originality — do not copy or spin the source material.
        - Provide depth, effort, and a conversational but professional tone.
        - Make the article comprehensive enough to be considered a reference piece.
        4. Structure & Engagement:
        - Write an engaging, click-worthy title using the target keyword.
        - Draft a long-form article (1500–2500 words).
        - Use structured headings (H1, H2, H3) for easy navigation.
        - Naturally incorporate the keyword with safe density (1–2%).
        - Add relevant subheadings that match common search queries.
        - Include actionable tips, examples, or step-by-step breakdowns.
        - Open with a compelling introduction and close with a strong conclusion.
        - Add an optional FAQ section covering related queries.
        5. User Value:
        - Address real user pain points and provide practical solutions.
        - Suggest relevant internal linking opportunities as [Link: topic].
        - Keep the content factually correct, useful, and engaging.

        CONTENT STRUCTURE:
        - Compelling Title (H1)
        - Introduction (2–3 engaging paragraphs)
        - Main Content with Multiple Sections (H2s and H3s)
        - Practical Tips/Examples
        - Conclusion with Call-to-Action
        - FAQ Section (optional but recommended)

        Please create a blog post that would rank well for "{keyword}" while providing trustworthy, comprehensive, and user-focused content. Format the output in clean Markdown.
        """
        
        print(f"Generating blog content for: {keyword}")
        print("This may take 30-60 seconds...")
        
        # Generate content using Gemini
        response = model.generate_content(
            prompt,
            generation_config=genai.types.GenerationConfig(
                temperature=0.7,
                top_p=0.8,
                top_k=40,
                max_output_tokens=4000,
            )
        )
        
        if response.text:
            print("Blog generated successfully!")
            return response.text
        else:
            raise Exception("No content generated by Gemini")
            
    except Exception as e:
        error_msg = f"Error generating blog with Gemini: {str(e)}"
        print(f"{error_msg}")