import google.generativeai as genai
import time
from typing import Dict, Any
from dotenv import load_dotenv
import os
load_dotenv()


GEMINI_API_KEY=os.getenv("GEMINI_API_KEY")

def configure_gemini(api_key: str):
    """Configure Gemini API with the provided key."""
    genai.configure(api_key=api_key)
    return genai.GenerativeModel('gemini-2.0-flash')

def generate_blog_with_gemini(selected_result: Dict[Any, Any]) -> str:
    """Generate a comprehensive blog post using Gemini API based on selected research result."""

    try:
        # Configure Gemini
        model = configure_gemini(GEMINI_API_KEY)
        
        # Extract information from selected result
        url = selected_result.get('url', '')
        title = selected_result.get('title', '')
        description = selected_result.get('description', '')
        keyword = selected_result.get('keyword', '')
        
        # Create comprehensive prompt for blog generation
        prompt = f"""
        You are an expert content writer and SEO specialist. Based on the following research data, create a comprehensive, engaging, and SEO-optimized blog post.

        RESEARCH DATA:
        - Target Keyword: {keyword}
        - Source URL: {url}
        - Page Title: {title}
        - Page Description: {description}

        BLOG POST REQUIREMENTS:
        1. Create an engaging, click-worthy title that includes the target keyword
        2. Write a comprehensive blog post (1500-2500 words) that covers the topic thoroughly
        3. Include proper headings (H1, H2, H3) for better structure
        4. Naturally incorporate the target keyword throughout the content (keyword density: 1-2%)
        5. Add relevant subheadings that users would search for
        6. Include actionable tips, examples, or step-by-step guides where applicable
        7. Write in a conversational, engaging tone that provides real value
        8. Add a compelling introduction and conclusion
        9. Include relevant internal linking opportunities (mention as [Link: topic])
        10. Ensure the content is original and not a copy of the source material

        CONTENT STRUCTURE:
        - Compelling Title (H1)
        - Engaging Introduction (2-3 paragraphs)
        - Main Content with Multiple Sections (H2s and H3s)
        - Practical Tips/Examples
        - Conclusion with Call-to-Action
        - FAQ Section (optional but recommended)

        Please create a blog post that would rank well for the keyword "{keyword}" while providing genuine value to readers. Make it comprehensive enough to be considered a pillar content piece.

        Format the output in clean Markdown format.
        """
        
        print(f"Generating blog content for: {keyword}")
        print("This may take 30-60 seconds...")
        
        # Generate content using Gemini
        response = model.generate_content(
            prompt,
            generation_config=genai.types.GenerationConfig(
                temperature=0.7,
                top_p=0.8,
                top_k=40,
                max_output_tokens=4000,
            )
        )
        
        if response.text:
            print("Blog generated successfully!")
            return response.text
        else:
            raise Exception("No content generated by Gemini")
            
    except Exception as e:
        error_msg = f"Error generating blog with Gemini: {str(e)}"
        print(f"{error_msg}")